import {  Caveat, Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  variable: "raleway",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "Caveat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Maysam Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${caveat.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
